repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]
        additional_dependencies: # requirements.txt + type stubs if available
          - pbr>=1.6
          - requests>=2.14.2
          - validators>=0.34
          - urllib3>=2.2.3
          - pydantic>=2.10.6
          
  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: venv/bin/pytest
        language: system
        pass_filenames: false