services:
  postgres:
    image: postgres:17
    container_name: postgres_db_openlabsx
    env_file:
      - .env
    ports:
      - "${POSTGRES_DEBUG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "${API_IP_ADDR:-127.0.0.1}:${API_PORT:-8000}:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network:
    driver: bridge
