services:
  postgres:
    image: postgres:17
    container_name: postgres_db_openlabsx
    env_file:
      - .env
    ports:
      - "${POSTGRES_DEBUG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Create admin user after app has started
  init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_init
    env_file:
      - .env
    environment:
      - HEALTH_CHECK_URL=http://fastapi:80/api/v1/health/ping
    command: ["python", "/code/src/scripts/create_admin.py"]
    depends_on:
      fastapi:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - fastapi_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "${API_IP_ADDR:-127.0.0.1}:${API_PORT:-8000}:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network:
    driver: bridge
