name: Main Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Create app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.AUTO_RELEASE_APP_ID }}
          private-key: ${{ secrets.AUTO_RELEASE_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Auto and Plugins
        run: npm install -g @auto-it/git-tag

      - name: Release with Auto
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: npx auto shipit